name: Deploy to GH Pages
# on - kiedy akcja ma się wykonać
on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      BASE_PATH: Portfolio-AdrianKorzan

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Remove unused files
        run: |
          rm -R .idea
          rm -R scss
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: /