name: Deploy to atthost server
on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      BASE_PATH: Portfolio-AdrianKorzan

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Remove unused files
        run: |
          rm -R scss
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.ATTHOST_SSH_PRIVATE_KEY }}
            ARGS: "-rltgoDzvO --delete"
            SOURCE: "./"
            REMOTE_HOST: ${{ secrets.ATTHOST_SHH_HOST }}
            REMOTE_PORT: 6022
            REMOTE_USER: ${{ secrets.ATTHOST_SSH_USER }}
            TARGET: ./websites/Portfolio-AdrianKorzan
            EXCLUDE: "/dist/, /node_modules/"